import json

with open('secret.json') as config_file:
    config = json.load(config_file)
    GEMINI_API_KEY = config['GEMINI_API_KEY']


CATEGORIES = [
    {"id": 1, "title": "Biophysics"},
    {"id": 2, "title": "Uncategorised content"},
    {"id": 4, "title": "Biochemistry"},
    {"id": 7, "title": "Medicine"},
    {"id": 8, "title": "Microbiology"},
    {"id": 10, "title": "Anatomy"},
    {"id": 11, "title": "Behavioral Neuroscience"},
    {"id": 12, "title": "Cell Biology"},
    {"id": 13, "title": "Genetics"},
    {"id": 14, "title": "Molecular Biology"},
    {"id": 15, "title": "Neuroscience"},
    {"id": 16, "title": "Physiology"},
    {"id": 17, "title": "Geography"},
    {"id": 19, "title": "Pharmacology"},
    {"id": 20, "title": "Computer Engineering"},
    {"id": 21, "title": "Biotechnology"},
    {"id": 23, "title": "Software Engineering"},
    {"id": 24, "title": "Evolutionary Biology"},
    {"id": 27, "title": "Economics"},
    {"id": 28, "title": "Paleontology"},
    {"id": 29, "title": "Geology"},
    {"id": 31, "title": "Environmental Chemistry"},
    {"id": 32, "title": "Geochemistry"},
    {"id": 34, "title": "Environmental Science"},
    {"id": 35, "title": "Limnology"},
    {"id": 36, "title": "Oceanography"},
    {"id": 37, "title": "Organic Chemistry"},
    {"id": 39, "title": "Ecology"},
    {"id": 42, "title": "Biological Engineering"},
    {"id": 44, "title": "Toxicology"},
    {"id": 45, "title": "Sociology"},
    {"id": 46, "title": "Immunology"},
    {"id": 47, "title": "Stereochemistry"},
    {"id": 54, "title": "Planetary Geology"},
    {"id": 55, "title": "Stellar Astronomy"},
    {"id": 56, "title": "Galactic Astronomy"},
    {"id": 57, "title": "Cosmology"},
    {"id": 58, "title": "Astrophysics"},
    {"id": 59, "title": "Planetary Science"},
    {"id": 61, "title": "Developmental Biology"},
    {"id": 62, "title": "Marine Biology"},
    {"id": 63, "title": "Parasitology"},
    {"id": 64, "title": "Cancer"},
    {"id": 65, "title": "Botany"},
    {"id": 66, "title": "Crystallography"},
    {"id": 69, "title": "Inorganic Chemistry"},
    {"id": 70, "title": "Molecular Physics"},
    {"id": 71, "title": "Nuclear Chemistry"},
    {"id": 73, "title": "Radiochemistry"},
    {"id": 75, "title": "Supramolecular Chemistry"},
    {"id": 76, "title": "Theoretical Computer Science"},
    {"id": 77, "title": "Applied Computer Science"},
    {"id": 78, "title": "Atmospheric Sciences"},
    {"id": 79, "title": "Geophysics"},
    {"id": 80, "title": "Hydrology"},
    {"id": 82, "title": "Mineralogy"},
    {"id": 84, "title": "Paleoclimatology"},
    {"id": 85, "title": "Palynology"},
    {"id": 86, "title": "Physical Geography"},
    {"id": 87, "title": "Soil Science"},
    {"id": 88, "title": "Agricultural Engineering"},
    {"id": 89, "title": "Aerospace Engineering"},
    {"id": 90, "title": "Genetic Engineering"},
    {"id": 91, "title": "Mechanical Engineering"},
    {"id": 92, "title": "Nuclear Engineering"},
    {"id": 94, "title": "Art"},
    {"id": 95, "title": "Design"},
    {"id": 97, "title": "Law"},
    {"id": 98, "title": "Literature"},
    {"id": 99, "title": "Performing Arts"},
    {"id": 100, "title": "Philosophy"},
    {"id": 102, "title": "Algebra"},
    {"id": 103, "title": "Geometry"},
    {"id": 104, "title": "Probability"},
    {"id": 105, "title": "Statistics"},
    {"id": 106, "title": "Science Policy"},
    {"id": 107, "title": "Applied Physics"},
    {"id": 108, "title": "Atomic Physics"},
    {"id": 109, "title": "Computational Physics"},
    {"id": 110, "title": "Condensed Matter Physics"},
    {"id": 111, "title": "Mechanics"},
    {"id": 112, "title": "Particle Physics"},
    {"id": 113, "title": "Plasma Physics"},
    {"id": 114, "title": "Quantum Mechanics"},
    {"id": 115, "title": "Solid Mechanics"},
    {"id": 116, "title": "Thermodynamics"},
    {"id": 117, "title": "Entropy"},
    {"id": 118, "title": "General Relativity"},
    {"id": 119, "title": "M-Theory"},
    {"id": 120, "title": "Special Relativity"},
    {"id": 122, "title": "Mental Health"},
    {"id": 125, "title": "Bioinformatics"},
    {"id": 126, "title": "History"},
    {"id": 127, "title": "Archaeology"},
    {"id": 128, "title": "Hematology"},
    {"id": 129, "title": "Education"},
    {"id": 130, "title": "Survey Results"},
    {"id": 131, "title": "Anesthesiology"},
    {"id": 132, "title": "Infectious Diseases"},
    {"id": 133, "title": "Plant Biology"},
    {"id": 134, "title": "Virology"},
    {"id": 135, "title": "ComputationalBiology"},
    {"id": 136, "title": "NMR Spectroscopy"},
    {"id": 137, "title": "Cheminformatics"},
    {"id": 138, "title": "Numerical Analysis"},
    {"id": 139, "title": "Pathology"},
    {"id": 140, "title": "Cardiology"},
    {"id": 141, "title": "Computational Chemistry"},
    {"id": 143, "title": "Solid Earth Sciences"},
    {"id": 144, "title": "Climate Science"},
    {"id": 145, "title": "Solar System, Solar Physics, Planets and Exoplanets"},
    {"id": 146, "title": "Space Science"},
    {"id": 147, "title": "Stars, Variable Stars"},
    {"id": 148, "title": "Instrumentation, Techniques, and Astronomical Observations"},
    {"id": 149, "title": "Interstellar and Intergalactic Matter"},
    {"id": 150, "title": "Extragalactic Astronomy"},
    {"id": 151, "title": "Biomarkers"},
    {"id": 152, "title": "Pathogenesis"},
    {"id": 153, "title": "Health Care"},
    {"id": 154, "title": "Diseases"},
    {"id": 155, "title": "Stem Cells"},
    {"id": 156, "title": "Systems Biology"},
    {"id": 157, "title": "Structural Biology"},
    {"id": 158, "title": "Biological Techniques"},
    {"id": 159, "title": "Zoology"},
    {"id": 160, "title": "Digital Humanities"},
    {"id": 161, "title": "Disability Studies"},
    {"id": 162, "title": "Drama"},
    {"id": 163, "title": "Entertainment"},
    {"id": 164, "title": "Environmental Humanities"},
    {"id": 165, "title": "Ethnic Studies"},
    {"id": 166, "title": "Gender studies"},
    {"id": 167, "title": "Language"},
    {"id": 168, "title": "Linguistics"},
    {"id": 169, "title": "Media Studies"},
    {"id": 170, "title": "Museology"},
    {"id": 171, "title": "Religious Studies"},
    {"id": 172, "title": "Rhetoric"},
    {"id": 173, "title": "Applied Psychology"},
    {"id": 174, "title": "Clinical Psychology"},
    {"id": 175, "title": "Developmental and Educational Psychology"},
    {"id": 176, "title": "Neuroscience and Physiological Psychology"},
    {"id": 177, "title": "Organizational Behavioral Psychology"},
    {"id": 178, "title": "Personality, Social and Criminal Psychology"},
    {"id": 179, "title": "Artificial Intelligence and Image Processing"},
    {"id": 180, "title": "Computation Theory and Mathematics"},
    {"id": 181, "title": "Computer Software"},
    {"id": 182, "title": "Data Format"},
    {"id": 183, "title": "Distributed Computing"},
    {"id": 184, "title": "Information Systems"},
    {"id": 185, "title": "Library and Information Studies"},
    {"id": 186, "title": "Classical and Physical Optics"},
    {"id": 187, "title": "Nonlinear Optics and Spectroscopy"},
    {"id": 188, "title": "Photonics, Optoelectronics and Optical Communications"},
    {"id": 189, "title": "Optical Physics not elsewhere classified"},
    {"id": 190, "title": "Degenerate Quantum Gases and Atom Optics"},
    {"id": 191, "title": "Quantum Optics"},
    {"id": 201, "title": "Atmospheric Aerosols"},
    {"id": 202, "title": "Atmospheric Dynamics"},
    {"id": 203, "title": "Atmospheric Radiation"},
    {"id": 204, "title": "Climate Change Processes"},
    {"id": 205, "title": "Climatology (excl. Climate Change Processes)"},
    {"id": 206, "title": "Cloud Physics"},
    {"id": 207, "title": "Meteorology"},
    {"id": 208, "title": "Tropospheric and Stratospheric Physics"},
    {"id": 209, "title": "Atmospheric Sciences not elsewhere classified"},
    {"id": 210, "title": "Exploration Geochemistry"},
    {"id": 211, "title": "Inorganic Geochemistry"},
    {"id": 212, "title": "Isotope Geochemistry"},
    {"id": 213, "title": "Organic Geochemistry"},
    {"id": 214, "title": "Geochemistry not elsewhere classified"},
    {"id": 215, "title": "Basin Analysis"},
    {"id": 216, "title": "Extraterrestrial Geology"},
    {"id": 217, "title": "Geochronology"},
    {"id": 218, "title": "Igneous and Metamorphic Petrology"},
    {"id": 219, "title": "Marine Geoscience"},
    {"id": 220, "title": "Mineralogy and Crystallography"},
    {"id": 221, "title": "Ore Deposit Petrology"},
    {"id": 222, "title": "Palaeontology (incl. Palynology)"},
    {"id": 223, "title": "Petroleum and Coal Geology"},
    {"id": 224, "title": "Sedimentology"},
    {"id": 225, "title": "Stratigraphy (incl. Biostratigraphy and Sequence Stratigraphy)"},
    {"id": 226, "title": "Structural Geology"},
    {"id": 227, "title": "Tectonics"},
    {"id": 228, "title": "Volcanology"},
    {"id": 229, "title": "Geology not elsewhere classified"},
    {"id": 230, "title": "Electrical and Electromagnetic Methods in Geophysics"},
    {"id": 231, "title": "Geodynamics"},
    {"id": 232, "title": "Geophysical Fluid Dynamics"},
    {"id": 233, "title": "Geothermics and Radiometrics"},
    {"id": 234, "title": "Gravimetrics"},
    {"id": 235, "title": "Magnetism and Palaeomagnetism"},
    {"id": 236, "title": "Seismology and Seismic Exploration"},
    {"id": 237, "title": "Geophysics not elsewhere classified"},
    {"id": 238, "title": "Biological Oceanography"},
    {"id": 239, "title": "Chemical Oceanography"},
    {"id": 240, "title": "Physical Oceanography"},
    {"id": 241, "title": "Oceanography not elsewhere classified"},
    {"id": 242, "title": "Geomorphology and Regolith and Landscape Evolution"},
    {"id": 243, "title": "Glaciology"},
    {"id": 244, "title": "Hydrogeology"},
    {"id": 245, "title": "Natural Hazards"},
    {"id": 246, "title": "Palaeoclimatology"},
    {"id": 247, "title": "Quaternary Environments"},
    {"id": 248, "title": "Surface Processes"},
    {"id": 249, "title": "Surfacewater Hydrology"},
    {"id": 250, "title": "Physical Geography and Environmental Geoscience not elsewhere classified"},
    {"id": 251, "title": "Earth Sciences not elsewhere classified"},
    {"id": 252, "title": "Ecological Impacts of Climate Change"},
    {"id": 253, "title": "Ecosystem Function"},
    {"id": 254, "title": "Invasive Species Ecology"},
    {"id": 255, "title": "Landscape Ecology"},
    {"id": 256, "title": "Ecological Applications not elsewhere classified"},
    {"id": 257, "title": "Conservation and Biodiversity"},
    {"id": 258, "title": "Environmental Education and Extension"},
    {"id": 259, "title": "Environmental Impact Assessment"},
    {"id": 260, "title": "Environmental Management"},
    {"id": 261, "title": "Environmental Monitoring"},
    {"id": 262, "title": "Environmental Rehabilitation (excl. Bioremediation)"},
    {"id": 263, "title": "Natural Resource Management"},
    {"id": 264, "title": "Wildlife and Habitat Management"},
    {"id": 265, "title": "Environmental Science and Management not elsewhere classified"},
    {"id": 266, "title": "Carbon Sequestration Science"},
    {"id": 267, "title": "Land Capability and Soil Degradation"},
    {"id": 268, "title": "Soil Biology"},
    {"id": 269, "title": "Soil Chemistry (excl. Carbon Sequestration Science)"},
    {"id": 270, "title": "Soil Physics"},
    {"id": 271, "title": "Soil Sciences not elsewhere classified"},
    {"id": 272, "title": "Environmental Sciences not elsewhere classified"},
    {"id": 289, "title": "Medical Biochemistry: Amino Acids and Metabolites"},
    {"id": 290, "title": "Medical Biochemistry: Carbohydrates"},
    {"id": 291, "title": "Medical Biochemistry: Inorganic Elements and Compounds"},
    {"id": 292, "title": "Medical Biochemistry: Lipids"},
    {"id": 293, "title": "Medical Biochemistry: Nucleic Acids"},
    {"id": 294, "title": "Medical Biochemistry: Proteins and Peptides (incl. Medical Proteomics)"},
    {"id": 295, "title": "Metabolic Medicine"},
    {"id": 296, "title": "Medical Biochemistry and Metabolomics not elsewhere classified"},
    {"id": 297, "title": "Cardiology (incl. Cardiovascular Diseases)"},
    {"id": 298, "title": "Haematology"},
    {"id": 299, "title": "Respiratory Diseases"},
    {"id": 300, "title": "Cardiovascular Medicine and Haematology not elsewhere classified"},
    {"id": 301, "title": "Anaesthesiology"},
    {"id": 302, "title": "Clinical Chemistry (diagnostics)"},
    {"id": 303, "title": "Clinical Microbiology"},
    {"id": 304, "title": "Dermatology"},
    {"id": 305, "title": "Emergency Medicine"},
    {"id": 306, "title": "Endocrinology"},
    {"id": 307, "title": "Gastroenterology and Hepatology"},
    {"id": 308, "title": "Geriatrics and Gerontology"},
    {"id": 310, "title": "Intensive Care"},
    {"id": 311, "title": "Medical Genetics (excl. Cancer Genetics)"},
    {"id": 312, "title": "Nephrology and Urology"},
    {"id": 313, "title": "Nuclear Medicine"},
    {"id": 314, "title": "Orthopaedics"},
    {"id": 315, "title": "Otorhinolaryngology"},
    {"id": 316, "title": "Pathology (excl. Oral Pathology)"},
    {"id": 317, "title": "Physiotherapy"},
    {"id": 318, "title": "Podiatry"},
    {"id": 319, "title": "Psychiatry (incl. Psychotherapy)"},
    {"id": 320, "title": "Radiology and Organ Imaging"},
    {"id": 321, "title": "Rehabilitation and Therapy (excl. Physiotherapy)"},
    {"id": 322, "title": "Rheumatology and Arthritis"},
    {"id": 323, "title": "Surgery"},
    {"id": 324, "title": "Venereology"},
    {"id": 325, "title": "Clinical Sciences not elsewhere classified"},
    {"id": 326, "title": "Chiropractic"},
    {"id": 327, "title": "Naturopathy"},
    {"id": 328, "title": "Traditional Chinese Medicine and Treatments"},
    {"id": 329, "title": "Complementary and Alternative Medicine not elsewhere classified"},
    {"id": 330, "title": "Dental Materials and Equipment"},
    {"id": 331, "title": "Dental Therapeutics, Pharmacology and Toxicology"},
    {"id": 332, "title": "Endodontics"},
    {"id": 333, "title": "Oral and Maxillofacial Surgery"},
    {"id": 334, "title": "Oral Medicine and Pathology"},
    {"id": 335, "title": "Orthodontics and Dentofacial Orthopaedics"},
    {"id": 336, "title": "Paedodontics"},
    {"id": 337, "title": "Periodontics"},
    {"id": 338, "title": "Special Needs Dentistry"},
    {"id": 339, "title": "Dentistry not elsewhere classified"},
    {"id": 340, "title": "Biomechanics"},
    {"id": 341, "title": "Exercise Physiology"},
    {"id": 342, "title": "Motor Control"},
    {"id": 343, "title": "Sports Medicine"},
    {"id": 344, "title": "Human Movement and Sports Science not elsewhere classified"},
    {"id": 345, "title": "Allergy"},
    {"id": 346, "title": "Applied Immunology (incl. Antibody Engineering, Xenotransplantation and T-cell Therapies)"},
    {"id": 347, "title": "Autoimmunity"},
    {"id": 348, "title": "Cellular Immunology"},
    {"id": 349, "title": "Humoural Immunology and Immunochemistry"},
    {"id": 350, "title": "Immunogenetics (incl. Genetic Immunology)"},
    {"id": 351, "title": "Innate Immunity"},
    {"id": 352, "title": "Transplantation Immunology"},
    {"id": 353, "title": "Tumour Immunology"},
    {"id": 354, "title": "Immunology not elsewhere classified"},
    {"id": 355, "title": "Medical Bacteriology"},
    {"id": 356, "title": "Medical Infection Agents (incl. Prions)"},
    {"id": 357, "title": "Medical Parasitology"},
    {"id": 358, "title": "Medical Virology"},
    {"id": 359, "title": "Medical Microbiology not elsewhere classified"},
    {"id": 360, "title": "Autonomic Nervous System"},
    {"id": 361, "title": "Cellular Nervous System"},
    {"id": 362, "title": "Central Nervous System"},
    {"id": 363, "title": "Neurology and Neuromuscular Diseases"},
    {"id": 364, "title": "Peripheral Nervous System"},
    {"id": 365, "title": "Sensory Systems"},
    {"id": 366, "title": "Neurosciences not elsewhere classified"},
    {"id": 367, "title": "Aged Care Nursing"},
    {"id": 368, "title": "Clinical Nursing: Primary (Preventative)"},
    {"id": 369, "title": "Clinical Nursing: Secondary (Acute Care)"},
    {"id": 370, "title": "Clinical Nursing: Tertiary (Rehabilitative)"},
    {"id": 371, "title": "Mental Health Nursing"},
    {"id": 372, "title": "Midwifery"},
    {"id": 373, "title": "Nursing not elsewhere classified"},
    {"id": 374, "title": "Clinical and Sports Nutrition"},
    {"id": 375, "title": "Dietetics and Nutrigenomics"},
    {"id": 376, "title": "Nutritional Physiology"},
    {"id": 377, "title": "Public Nutrition Intervention"},
    {"id": 378, "title": "Nutrition and Dietetics not elsewhere classified"},
    {"id": 379, "title": "Cancer Cell Biology"},
    {"id": 380, "title": "Cancer Diagnosis"},
    {"id": 381, "title": "Cancer Genetics"},
    {"id": 382, "title": "Cancer Therapy (excl. Chemotherapy and Radiation Therapy)"},
    {"id": 383, "title": "Chemotherapy"},
    {"id": 384, "title": "Haematological Tumours"},
    {"id": 385, "title": "Molecular Targets"},
    {"id": 386, "title": "Radiation Therapy"},
    {"id": 387, "title": "Solid Tumours"},
    {"id": 388, "title": "Oncology and Carcinogenesis not elsewhere classified"},
    {"id": 389, "title": "Ophthalmology"},
    {"id": 390, "title": "Optical Technology"},
    {"id": 391, "title": "Vision Science"},
    {"id": 392, "title": "Ophthalmology and Optometry not elsewhere classified"},
    {"id": 393, "title": "Foetal Development and Medicine"},
    {"id": 394, "title": "Obstetrics and Gynaecology"},
    {"id": 395, "title": "Paediatrics"},
    {"id": 396, "title": "Reproduction"},
    {"id": 397, "title": "Paediatrics and Reproductive Medicine not elsewhere classified"},
    {"id": 398, "title": "Basic Pharmacology"},
    {"id": 399, "title": "Clinical Pharmacology and Therapeutics"},
    {"id": 400, "title": "Clinical Pharmacy and Pharmacy Practice"},
    {"id": 401, "title": "Pharmaceutical Sciences"},
    {"id": 402, "title": "Pharmacogenomics"},
    {"id": 403, "title": "Toxicology (incl. Clinical Toxicology)"},
    {"id": 404, "title": "Pharmacology and Pharmaceutical Sciences not elsewhere classified"},
    {"id": 405, "title": "Cell Physiology"},
    {"id": 406, "title": "Human Biophysics"},
    {"id": 407, "title": "Systems Physiology"},
    {"id": 408, "title": "Medical Physiology not elsewhere classified"},
    {"id": 409, "title": "Aboriginal and Torres Strait Islander Health"},
    {"id": 410, "title": "Aged Health Care"},
    {"id": 411, "title": "Care for Disabled"},
    {"id": 412, "title": "Community Child Health"},
    {"id": 413, "title": "Environmental and Occupational Health and Safety"},
    {"id": 414, "title": "Epidemiology"},
    {"id": 415, "title": "Family Care"},
    {"id": 416, "title": "Health and Community Services"},
    {"id": 417, "title": "Health Care Administration"},
    {"id": 418, "title": "Health Counselling"},
    {"id": 419, "title": "Health Information Systems (incl. Surveillance)"},
    {"id": 420, "title": "Health Promotion"},
    {"id": 421, "title": "Maori Health"},
    {"id": 423, "title": "Pacific Peoples Health"},
    {"id": 424, "title": "Preventive Medicine"},
    {"id": 425, "title": "Primary Health Care"},
    {"id": 426, "title": "Residential Client Care"},
    {"id": 427, "title": "Public Health and Health Services not elsewhere classified"},
    {"id": 428, "title": "Medical and Health Sciences not elsewhere classified"},
    {"id": 434, "title": "Biological Psychology (Neuropsychology, Psychopharmacology, Physiological Psychology)"},
    {"id": 435, "title": "Developmental Psychology and Ageing"},
    {"id": 436, "title": "Educational Psychology"},
    {"id": 437, "title": "Forensic Psychology"},
    {"id": 438, "title": "Gender Psychology"},
    {"id": 439, "title": "Health, Clinical and Counselling Psychology"},
    {"id": 440, "title": "Industrial and Organisational Psychology"},
    {"id": 441, "title": "Personality, Abilities and Assessment"},
    {"id": 442, "title": "Psychological Methodology, Design and Analysis"},
    {"id": 443, "title": "Psychology of Religion"},
    {"id": 444, "title": "Sensory Processes, Perception and Performance"},
    {"id": 445, "title": "Social and Community Psychology"},
    {"id": 446, "title": "Sport and Exercise Psychology"},
    {"id": 447, "title": "Psychology not elsewhere classified"},
    {"id": 448, "title": "Computer Perception, Memory and Attention"},
    {"id": 449, "title": "Decision Making"},
    {"id": 450, "title": "Knowledge Representation and Machine Learning"},
    {"id": 451, "title": "Linguistic Processes (incl. Speech Production and Comprehension)"},
    {"id": 452, "title": "Neurocognitive Patterns and Neural Networks"},
    {"id": 453, "title": "Cognitive Science not elsewhere classified"},
    {"id": 454, "title": "Psychology and Cognitive Sciences not elsewhere classified"},
    {"id": 492, "title": "Astrobiology"},
    {"id": 493, "title": "Astronomical and Space Instrumentation"},
    {"id": 494, "title": "Cosmology and Extragalactic Astronomy"},
    {"id": 496, "title": "General Relativity and Gravitational Waves"},
    {"id": 497, "title": "High Energy Astrophysics; Cosmic Rays"},
    {"id": 498, "title": "Mesospheric, Ionospheric and Magnetospheric Physics"},
    {"id": 499, "title": "Planetary Science (excl. Extraterrestrial Geology)"},
    {"id": 500, "title": "Space and Solar Physics"},
    {"id": 501, "title": "Stellar Astronomy and Planetary Systems"},
    {"id": 502, "title": "Astronomical and Space Sciences not elsewhere classified"},
    {"id": 516, "title": "Aerodynamics (excl. Hypersonic Aerodynamics)"},
    {"id": 517, "title": "Aerospace Materials"},
    {"id": 518, "title": "Aerospace Structures"},
    {"id": 519, "title": "Aircraft Performance and Flight Control Systems"},
    {"id": 520, "title": "Avionics"},
    {"id": 521, "title": "Flight Dynamics"},
    {"id": 522, "title": "Hypersonic Propulsion and Hypersonic Aerodynamics"},
    {"id": 523, "title": "Satellite, Space Vehicle and Missile Design and Testing"},
    {"id": 524, "title": "Aerospace Engineering not elsewhere classified"},
    {"id": 525, "title": "Automotive Combustion and Fuel Engineering (incl. Alternative/Renewable Fuels)"},
    {"id": 526, "title": "Automotive Engineering Materials"},
    {"id": 527, "title": "Automotive Mechatronics"},
    {"id": 528, "title": "Automotive Safety Engineering"},
    {"id": 529, "title": "Hybrid Vehicles and Powertrains"},
    {"id": 530, "title": "Automotive Engineering not elsewhere classified"},
    {"id": 531, "title": "Biomaterials"},
    {"id": 532, "title": "Biomechanical Engineering"},
    {"id": 533, "title": "Biomedical Instrumentation"},
    {"id": 534, "title": "Medical Devices"},
    {"id": 535, "title": "Rehabilitation Engineering"},
    {"id": 536, "title": "Biomedical Engineering not elsewhere classified"},
    {"id": 537, "title": "Carbon Capture Engineering (excl. Sequestration)"},
    {"id": 538, "title": "Catalytic Process Engineering"},
    {"id": 539, "title": "Chemical Engineering Design"},
    {"id": 540, "title": "Membrane and Separation Technologies"},
    {"id": 541, "title": "Non-automotive Combustion and Fuel Engineering (incl. Alternative/Renewable Fuels)"},
    {"id": 542, "title": "Powder and Particle Technology"},
    {"id": 543, "title": "Process Control and Simulation"},
    {"id": 544, "title": "Rheology"},
    {"id": 545, "title": "Wastewater Treatment Processes"},
    {"id": 546, "title": "Water Treatment Processes"},
    {"id": 547, "title": "Chemical Engineering not elsewhere classified"},
    {"id": 548, "title": "Civil Geotechnical Engineering"},
    {"id": 549, "title": "Construction Engineering"},
    {"id": 550, "title": "Construction Materials"},
    {"id": 551, "title": "Earthquake Engineering"},
    {"id": 552, "title": "Infrastructure Engineering and Asset Management"},
    {"id": 553, "title": "Structural Engineering"},
    {"id": 554, "title": "Transport Engineering"},
    {"id": 555, "title": "Water Quality Engineering"},
    {"id": 556, "title": "Water Resources Engineering"},
    {"id": 557, "title": "Civil Engineering not elsewhere classified"},
    {"id": 558, "title": "Circuits and Systems"},
    {"id": 559, "title": "Control Systems, Robotics and Automation"},
    {"id": 560, "title": "Industrial Electronics"},
    {"id": 561, "title": "Microelectronics and Integrated Circuits"},
    {"id": 562, "title": "Photodetectors, Optical Sensors and Solar Cells"},
    {"id": 563, "title": "Photonics and Electro-Optical Engineering (excl. Communications)"},
    {"id": 564, "title": "Power and Energy Systems Engineering (excl. Renewable Power)"},
    {"id": 565, "title": "Renewable Power and Energy Systems Engineering (excl. Solar Cells)"},
    {"id": 566, "title": "Signal Processing"},
    {"id": 567, "title": "Electrical and Electronic Engineering not elsewhere classified"},
    {"id": 568, "title": "Environmental Engineering Design"},
    {"id": 569, "title": "Environmental Engineering Modelling"},
    {"id": 570, "title": "Environmental Technologies"},
    {"id": 571, "title": "Environmental Engineering not elsewhere classified"},
    {"id": 572, "title": "Food Chemistry and Molecular Gastronomy (excl. Wine)"},
    {"id": 573, "title": "Food Engineering"},
    {"id": 574, "title": "Food Nutritional Balance"},
    {"id": 575, "title": "Food Packaging, Preservation and Safety"},
    {"id": 576, "title": "Food Processing"},
    {"id": 577, "title": "Wine Chemistry and Wine Sensory Science"},
    {"id": 578, "title": "Food Sciences not elsewhere classified"},
    {"id": 579, "title": "Cartography"},
    {"id": 580, "title": "Geodesy"},
    {"id": 581, "title": "Geospatial Information Systems"},
    {"id": 582, "title": "Navigation and Position Fixing"},
    {"id": 583, "title": "Photogrammetry and Remote Sensing"},
    {"id": 584, "title": "Surveying (incl. Hydrographic Surveying)"},
    {"id": 585, "title": "Geomatic Engineering not elsewhere classified"},
    {"id": 586, "title": "CAD/CAM Systems"},
    {"id": 587, "title": "Flexible Manufacturing Systems"},
    {"id": 588, "title": "Machine Tools"},
    {"id": 589, "title": "Machining"},
    {"id": 590, "title": "Manufacturing Management"},
    {"id": 591, "title": "Manufacturing Processes and Technologies (excl. Textiles)"},
    {"id": 592, "title": "Manufacturing Robotics and Mechatronics (excl. Automotive Mechatronics)"},
    {"id": 593, "title": "Manufacturing Safety and Quality"},
    {"id": 594, "title": "Microtechnology"},
    {"id": 595, "title": "Packaging, Storage and Transportation (excl. Food and Agricultural Products)"},
    {"id": 596, "title": "Precision Engineering"},
    {"id": 597, "title": "Textile Technology"},
    {"id": 598, "title": "Manufacturing Engineering not elsewhere classified"},
    {"id": 599, "title": "Marine Engineering"},
    {"id": 600, "title": "Naval Architecture"},
    {"id": 601, "title": "Ocean Engineering"},
    {"id": 602, "title": "Ship and Platform Hydrodynamics"},
    {"id": 603, "title": "Ship and Platform Structures"},
    {"id": 604, "title": "Special Vehicles"},
    {"id": 605, "title": "Maritime Engineering not elsewhere classified"},
    {"id": 606, "title": "Ceramics"},
    {"id": 607, "title": "Composite and Hybrid Materials"},
    {"id": 608, "title": "Compound Semiconductors"},
    {"id": 609, "title": "Elemental Semiconductors"},
    {"id": 610, "title": "Functional Materials"},
    {"id": 611, "title": "Glass"},
    {"id": 612, "title": "Metals and Alloy Materials"},
    {"id": 613, "title": "Organic Semiconductors"},
    {"id": 614, "title": "Polymers and Plastics"},
    {"id": 615, "title": "Timber, Pulp and Paper"},
    {"id": 616, "title": "Materials Engineering not elsewhere classified"},
    {"id": 617, "title": "Acoustics and Noise Control (excl. Architectural Acoustics)"},
    {"id": 618, "title": "Automation and Control Engineering"},
    {"id": 619, "title": "Autonomous Vehicles"},
    {"id": 620, "title": "Dynamics, Vibration and Vibration Control"},
    {"id": 621, "title": "Energy Generation, Conversion and Storage Engineering"},
    {"id": 622, "title": "Microelectromechanical Systems (MEMS)"},
    {"id": 623, "title": "Numerical Modelling and Mechanical Characterisation"},
    {"id": 625, "title": "Tribology"},
    {"id": 626, "title": "Mechanical Engineering not elsewhere classified"},
    {"id": 627, "title": "Electrometallurgy"},
    {"id": 628, "title": "Geomechanics and Resources Geotechnical Engineering"},
    {"id": 629, "title": "Hydrometallurgy"},
    {"id": 630, "title": "Mineral Processing/Beneficiation"},
    {"id": 631, "title": "Mining Engineering"},
    {"id": 632, "title": "Petroleum and Reservoir Engineering"},
    {"id": 633, "title": "Pyrometallurgy"},
    {"id": 634, "title": "Resources Engineering and Extractive Metallurgy not elsewhere classified"},
    {"id": 635, "title": "Computational Fluid Dynamics"},
    {"id": 636, "title": "Computational Heat Transfer"},
    {"id": 637, "title": "Engineering Practice"},
    {"id": 638, "title": "Fluidisation and Fluid Mechanics"},
    {"id": 639, "title": "Heat and Mass Transfer Operations"},
    {"id": 640, "title": "Nuclear Engineering (incl. Fuel Enrichment and Waste Processing and Storage)"},
    {"id": 641, "title": "Risk Engineering (excl. Earthquake Engineering)"},
    {"id": 642, "title": "Turbulent Flows"},
    {"id": 643, "title": "Interdisciplinary Engineering not elsewhere classified"},
    {"id": 645, "title": "Engineering Instrumentation"},
    {"id": 646, "title": "Engineering not elsewhere classified"},
    {"id": 655, "title": "Analytical Biochemistry"},
    {"id": 657, "title": "Cell Development, Proliferation and Death"},
    {"id": 658, "title": "Cell Metabolism"},
    {"id": 659, "title": "Cell Neurochemistry"},
    {"id": 660, "title": "Cellular Interactions (incl. Adhesion, Matrix, Cell Wall)"},
    {"id": 661, "title": "Enzymes"},
    {"id": 662, "title": "Protein Trafficking"},
    {"id": 663, "title": "Proteomics and Intermolecular Interactions (excl. Medical Proteomics)"},
    {"id": 664, "title": "Receptors and Membrane Biology"},
    {"id": 665, "title": "Signal Transduction"},
    {"id": 666, "title": "Structural Biology (incl. Macromolecular Modelling)"},
    {"id": 667, "title": "Synthetic Biology"},
    {"id": 669, "title": "Biochemistry and Cell Biology not elsewhere classified"},
    {"id": 670, "title": "Behavioural Ecology"},
    {"id": 671, "title": "Community Ecology (excl. Invasive Species Ecology)"},
    {"id": 672, "title": "Ecological Physiology"},
    {"id": 673, "title": "Freshwater Ecology"},
    {"id": 674, "title": "Marine and Estuarine Ecology (incl. Marine Ichthyology)"},
    {"id": 675, "title": "Palaeoecology"},
    {"id": 676, "title": "Population Ecology"},
    {"id": 677, "title": "Terrestrial Ecology"},
    {"id": 678, "title": "Ecology not elsewhere classified"},
    {"id": 679, "title": "Animal Systematics and Taxonomy"},
    {"id": 680, "title": "Biogeography and Phylogeography"},
    {"id": 681, "title": "Biological Adaptation"},
    {"id": 682, "title": "Ethology and Sociobiology"},
    {"id": 683, "title": "Evolution of Developmental Systems"},
    {"id": 684, "title": "Evolutionary Impacts of Climate Change"},
    {"id": 685, "title": "Host-Parasite Interactions"},
    {"id": 686, "title": "Life Histories"},
    {"id": 687, "title": "Phylogeny and Comparative Analysis"},
    {"id": 688, "title": "Plant Systematics and Taxonomy"},
    {"id": 689, "title": "Speciation and Extinction"},
    {"id": 690, "title": "Evolutionary Biology not elsewhere classified"},
    {"id": 691, "title": "Anthropological Genetics"},
    {"id": 692, "title": "Cell and Nuclear Division"},
    {"id": 693, "title": "Developmental Genetics (incl. Sex Determination)"},
    {"id": 694, "title": "Epigenetics (incl. Genome Methylation and Epigenomics)"},
    {"id": 695, "title": "Gene Expression (incl. Microarray and other genome-wide approaches)"},
    {"id": 696, "title": "Genetic Immunology"},
    {"id": 697, "title": "Genome Structure and Regulation"},
    {"id": 698, "title": "Genomics"},
    {"id": 699, "title": "Molecular Evolution"},
    {"id": 700, "title": "Neurogenetics"},
    {"id": 701, "title": "Population, Ecological and Evolutionary Genetics"},
    {"id": 702, "title": "Quantitative Genetics (incl. Disease and Trait Mapping Genetics)"},
    {"id": 703, "title": "Genetics not elsewhere classified"},
    {"id": 704, "title": "Bacteriology"},
    {"id": 705, "title": "Infectious Agents"},
    {"id": 706, "title": "Microbial Genetics"},
    {"id": 707, "title": "Microbial Ecology"},
    {"id": 708, "title": "Mycology"},
    {"id": 710, "title": "Microbiology not elsewhere classified"},
    {"id": 711, "title": "Animal Physiology - Biophysics"},
    {"id": 712, "title": "Animal Physiology - Cell"},
    {"id": 713, "title": "Animal Physiology - Systems"},
    {"id": 714, "title": "Comparative Physiology"},
    {"id": 715, "title": "Physiology not elsewhere classified"},
    {"id": 716, "title": "Phycology (incl. Marine Grasses)"},
    {"id": 717, "title": "Plant Cell and Molecular Biology"},
    {"id": 718, "title": "Plant Developmental and Reproductive Biology"},
    {"id": 719, "title": "Plant Pathology"},
    {"id": 720, "title": "Plant Physiology"},
    {"id": 721, "title": "Plant Biology not elsewhere classified"},
    {"id": 722, "title": "Animal Behaviour"},
    {"id": 723, "title": "Animal Cell and Molecular Biology"},
    {"id": 724, "title": "Animal Developmental and Reproductive Biology"},
    {"id": 725, "title": "Animal Immunology"},
    {"id": 726, "title": "Animal Neurobiology"},
    {"id": 727, "title": "Animal Physiological Ecology"},
    {"id": 728, "title": "Animal Structure and Function"},
    {"id": 729, "title": "Invertebrate Biology"},
    {"id": 730, "title": "Vertebrate Biology"},
    {"id": 731, "title": "Zoology not elsewhere classified"},
    {"id": 732, "title": "Forensic Biology"},
    {"id": 733, "title": "Global Change Biology"},
    {"id": 734, "title": "Biological Sciences not elsewhere classified"},
    {"id": 747, "title": "Computational Biology"},
    {"id": 772, "title": "Algebra and Number Theory"},
    {"id": 773, "title": "Algebraic and Differential Geometry"},
    {"id": 774, "title": "Category Theory, K Theory, Homological Algebra"},
    {"id": 775, "title": "Combinatorics and Discrete Mathematics (excl. Physical Combinatorics)"},
    {"id": 776, "title": "Group Theory and Generalisations"},
    {"id": 777, "title": "Lie Groups, Harmonic and Fourier Analysis"},
    {"id": 778, "title": "Mathematical Logic, Set Theory, Lattices and Universal Algebra"},
    {"id": 779, "title": "Operator Algebras and Functional Analysis"},
    {"id": 780, "title": "Ordinary Differential Equations, Difference Equations and Dynamical Systems"},
    {"id": 781, "title": "Partial Differential Equations"},
    {"id": 782, "title": "Real and Complex Functions (incl. Several Variables)"},
    {"id": 783, "title": "Topology"},
    {"id": 784, "title": "Pure Mathematics not elsewhere classified"},
    {"id": 785, "title": "Approximation Theory and Asymptotic Methods"},
    {"id": 786, "title": "Biological Mathematics"},
    {"id": 787, "title": "Calculus of Variations, Systems Theory and Control Theory"},
    {"id": 788, "title": "Dynamical Systems in Applications"},
    {"id": 789, "title": "Financial Mathematics"},
    {"id": 790, "title": "Operations Research"},
    {"id": 791, "title": "Theoretical and Applied Mechanics"},
    {"id": 792, "title": "Applied Mathematics not elsewhere classified"},
    {"id": 794, "title": "Numerical Solution of Differential and Integral Equations"},
    {"id": 795, "title": "Optimisation"},
    {"id": 796, "title": "Numerical and Computational Mathematics not elsewhere classified"},
    {"id": 797, "title": "Applied Statistics"},
    {"id": 798, "title": "Biostatistics"},
    {"id": 799, "title": "Forensic Statistics"},
    {"id": 800, "title": "Probability Theory"},
    {"id": 801, "title": "Statistical Theory"},
    {"id": 802, "title": "Stochastic Analysis and Modelling"},
    {"id": 803, "title": "Statistics not elsewhere classified"},
    {"id": 804, "title": "Algebraic Structures in Mathematical Physics"},
    {"id": 805, "title": "Integrable Systems (Classical and Quantum)"},
    {"id": 806, "title": "Mathematical Aspects of Classical Mechanics, Quantum Mechanics and Quantum Information Theory"},
    {"id": 807, "title": "Mathematical Aspects of General Relativity"},
    {"id": 808, "title": "Mathematical Aspects of Quantum and Conformal Field Theory, Quantum Gravity and String Theory"},
    {"id": 809, "title": "Statistical Mechanics, Physical Combinatorics and Mathematical Aspects of Condensed Matter"},
    {"id": 810, "title": "Mathematical Physics not elsewhere classified"},
    {"id": 811, "title": "Mathematical Sciences not elsewhere classified"},
    {"id": 818, "title": "Analytical Spectrometry"},
    {"id": 819, "title": "Electroanalytical Chemistry"},
    {"id": 820, "title": "Flow Analysis"},
    {"id": 821, "title": "Immunological and Bioassay Methods"},
    {"id": 822, "title": "Instrumental Methods (excl. Immunological and Bioassay Methods)"},
    {"id": 823, "title": "Quality Assurance, Chemometrics, Traceability and Metrological Chemistry"},
    {"id": 824, "title": "Sensor Technology (Chemical aspects)"},
    {"id": 825, "title": "Separation Science"},
    {"id": 826, "title": "Analytical Chemistry not elsewhere classified"},
    {"id": 827, "title": "Bioinorganic Chemistry"},
    {"id": 828, "title": "f-Block Chemistry"},
    {"id": 829, "title": "Inorganic Green Chemistry"},
    {"id": 830, "title": "Main Group Metal Chemistry"},
    {"id": 831, "title": "Non-metal Chemistry"},
    {"id": 832, "title": "Solid State Chemistry"},
    {"id": 833, "title": "Transition Metal Chemistry"},
    {"id": 834, "title": "Inorganic Chemistry not elsewhere classified"},
    {"id": 835, "title": "Chemical Characterisation of Materials"},
    {"id": 836, "title": "Nanochemistry and Supramolecular Chemistry"},
    {"id": 837, "title": "Optical Properties of Materials"},
    {"id": 838, "title": "Physical Chemistry of Materials"},
    {"id": 839, "title": "Polymerisation Mechanisms"},
    {"id": 840, "title": "Synthesis of Materials"},
    {"id": 841, "title": "Theory and Design of Materials"},
    {"id": 842, "title": "Macromolecular and Materials Chemistry not elsewhere classified"},
    {"id": 843, "title": "Biologically Active Molecules"},
    {"id": 844, "title": "Biomolecular Modelling and Design"},
    {"id": 845, "title": "Characterisation of Biological Macromolecules"},
    {"id": 846, "title": "Cheminformatics and Quantitative Structure-Activity Relationships"},
    {"id": 847, "title": "Molecular Medicine"},
    {"id": 848, "title": "Proteins and Peptides"},
    {"id": 849, "title": "Medicinal and Biomolecular Chemistry not elsewhere classified"},
    {"id": 850, "title": "Free Radical Chemistry"},
    {"id": 851, "title": "Natural Products Chemistry"},
    {"id": 852, "title": "Organic Chemical Synthesis"},
    {"id": 853, "title": "Organic Green Chemistry"},
    {"id": 854, "title": "Physical Organic Chemistry"},
    {"id": 855, "title": "Organic Chemistry not elsewhere classified"},
    {"id": 856, "title": "Catalysis and Mechanisms of Reactions"},
    {"id": 857, "title": "Chemical Thermodynamics and Energetics"},
    {"id": 858, "title": "Colloid and Surface Chemistry"},
    {"id": 859, "title": "Electrochemistry"},
    {"id": 860, "title": "Solution Chemistry"},
    {"id": 861, "title": "Structural Chemistry and Spectroscopy"},
    {"id": 862, "title": "Transport Properties and Non-equilibrium Processes"},
    {"id": 863, "title": "Physical Chemistry not elsewhere classified"},
    {"id": 864, "title": "Quantum Chemistry"},
    {"id": 865, "title": "Radiation and Matter"},
    {"id": 866, "title": "Reaction Kinetics and Dynamics"},
    {"id": 867, "title": "Statistical Mechanics in Chemistry"},
    {"id": 868, "title": "Theoretical and Computational Chemistry not elsewhere classified"},
    {"id": 869, "title": "Environmental Chemistry (incl. Atmospheric Chemistry)"},
    {"id": 870, "title": "Forensic Chemistry"},
    {"id": 871, "title": "Industrial Chemistry"},
    {"id": 872, "title": "Organometallic Chemistry"},
    {"id": 873, "title": "Chemical Sciences not elsewhere classified"},
    {"id": 888, "title": "Atomic and Molecular Physics"},
    {"id": 889, "title": "Nuclear Physics"},
    {"id": 891, "title": "Plasma Physics; Fusion Plasmas; Electrical Discharges"},
    {"id": 892, "title": "Atomic, Molecular, Nuclear, Particle and Plasma Physics not elsewhere classified"},
    {"id": 893, "title": "Acoustics and Acoustical Devices; Waves"},
    {"id": 894, "title": "Electrostatics and Electrodynamics"},
    {"id": 895, "title": "Fluid Physics"},
    {"id": 896, "title": "Thermodynamics and Statistical Physics"},
    {"id": 897, "title": "Classical Physics not elsewhere classified"},
    {"id": 898, "title": "Condensed Matter Characterisation Technique Development"},
    {"id": 899, "title": "Condensed Matter Imaging"},
    {"id": 900, "title": "Condensed Matter Modelling and Density Functional Theory"},
    {"id": 901, "title": "Electronic and Magnetic Properties of Condensed Matter; Superconductivity"},
    {"id": 902, "title": "Soft Condensed Matter"},
    {"id": 903, "title": "Surfaces and Structural Properties of Condensed Matter"},
    {"id": 904, "title": "Condensed Matter Physics not elsewhere classified"},
    {"id": 905, "title": "Lasers and Quantum Electronics"},
    {"id": 908, "title": "Field Theory and String Theory"},
    {"id": 909, "title": "Quantum Information, Computation and Communication"},
    {"id": 910, "title": "Quantum Physics not elsewhere classified"},
    {"id": 911, "title": "Biological Physics"},
    {"id": 912, "title": "Complex Physical Systems"},
    {"id": 913, "title": "Medical Physics"},
    {"id": 914, "title": "Synchrotrons; Accelerators; Instruments and Techniques"},
    {"id": 915, "title": "Physical Sciences not elsewhere classified"},
    {"id": 931, "title": "Information Systems not elsewhere classified"},
    {"id": 932, "title": "Health Informatics"},
    {"id": 933, "title": "Human Information Behaviour"},
    {"id": 934, "title": "Information Retrieval and Web Search"},
    {"id": 935, "title": "Informetrics"},
    {"id": 936, "title": "Librarianship"},
    {"id": 937, "title": "Organisation of Information and Knowledge Resources"},
    {"id": 938, "title": "Records and Information Management (excl. Business Records and Information Management)"},
    {"id": 939, "title": "Social and Community Informatics"},
    {"id": 940, "title": "Library and Information Studies not elsewhere classified"},
    {"id": 941, "title": "Information and Computing Sciences not elsewhere classified"},
    {"id": 942, "title": "Adaptive Agents and Intelligent Robotics"},
    {"id": 943, "title": "Artificial Life"},
    {"id": 944, "title": "Computer Graphics"},
    {"id": 945, "title": "Computer Vision"},
    {"id": 946, "title": "Expert Systems"},
    {"id": 947, "title": "Image Processing"},
    {"id": 948, "title": "Natural Language Processing"},
    {"id": 949, "title": "Neural, Evolutionary and Fuzzy Computation"},
    {"id": 950, "title": "Pattern Recognition and Data Mining"},
    {"id": 951, "title": "Simulation and Modelling"},
    {"id": 952, "title": "Virtual Reality and Related Simulation"},
    {"id": 953, "title": "Artificial Intelligence and Image Processing not elsewhere classified"},
    {"id": 954, "title": "Analysis of Algorithms and Complexity"},
    {"id": 955, "title": "Applied Discrete Mathematics"},
    {"id": 956, "title": "Computational Logic and Formal Languages"},
    {"id": 957, "title": "Mathematical Software"},
    {"id": 958, "title": "Numerical Computation"},
    {"id": 959, "title": "Computation Theory and Mathematics not elsewhere classified"},
    {"id": 960, "title": "Bioinformatics Software"},
    {"id": 961, "title": "Computer System Architecture"},
    {"id": 962, "title": "Computer System Security"},
    {"id": 963, "title": "Concurrent Programming"},
    {"id": 964, "title": "Multimedia Programming"},
    {"id": 965, "title": "Open Software"},
    {"id": 966, "title": "Operating Systems"},
    {"id": 967, "title": "Programming Languages"},
    {"id": 969, "title": "Computer Software not elsewhere classified"},
    {"id": 970, "title": "Coding and Information Theory"},
    {"id": 971, "title": "Data Encryption"},
    {"id": 972, "title": "Data Structures"},
    {"id": 973, "title": "Markup Languages"},
    {"id": 974, "title": "Data Format not elsewhere classified"},
    {"id": 975, "title": "Distributed and Grid Systems"},
    {"id": 976, "title": "Mobile Technologies"},
    {"id": 977, "title": "Networking and Communications"},
    {"id": 978, "title": "Ubiquitous Computing"},
    {"id": 979, "title": "Web Technologies (excl. Web Search)"},
    {"id": 980, "title": "Distributed Computing not elsewhere classified"},
    {"id": 981, "title": "Aboriginal and Torres Strait Islander Information and Knowledge Systems"},
    {"id": 982, "title": "Computer-Human Interaction"},
    {"id": 983, "title": "Conceptual Modelling"},
    {"id": 984, "title": "Database Management"},
    {"id": 985, "title": "Decision Support and Group Support Systems"},
    {"id": 986, "title": "Global Information Systems"},
    {"id": 987, "title": "Information Engineering and Theory"},
    {"id": 988, "title": "Information Systems Development Methodologies"},
    {"id": 989, "title": "Information Systems Management"},
    {"id": 990, "title": "Information Systems Organisation"},
    {"id": 991, "title": "Information Systems Theory"},
    {"id": 992, "title": "Interorganisational Information Systems and Web Services"},
    {"id": 995, "title": "Aboriginal and Torres Strait Islander Performing Arts"},
    {"id": 996, "title": "Creative Writing (incl. Playwriting)"},
    {"id": 997, "title": "Dance"},
    {"id": 998, "title": "Drama, Theatre and Performance Studies"},
    {"id": 999, "title": "Maori Performing Arts"},
    {"id": 1000, "title": "Music Composition"},
    {"id": 1001, "title": "Music Performance"},
    {"id": 1002, "title": "Music Therapy"},
    {"id": 1003, "title": "Musicology and Ethnomusicology"},
    {"id": 1004, "title": "Pacific Peoples Performing Arts"},
    {"id": 1005, "title": "Performing Arts and Creative Writing not elsewhere classified"},
    {"id": 1006, "title": "Continuing and Community Education"},
    {"id": 1007, "title": "Early Childhood Education (excl. Maori)"},
    {"id": 1008, "title": "Higher Education"},
    {"id": 1009, "title": "Primary Education (excl. Maori)"},
    {"id": 1010, "title": "Secondary Education"},
    {"id": 1011, "title": "Technical, Further and Workplace Education"},
    {"id": 1012, "title": "Education systems not elsewhere classified"},
    {"id": 1013, "title": "Agricultural Economics"},
    {"id": 1014, "title": "Economic Development and Growth"},
    {"id": 1015, "title": "Economic History"},
    {"id": 1016, "title": "Economics of Education"},
    {"id": 1017, "title": "Environment and Resource Economics"},
    {"id": 1018, "title": "Experimental Economics"},
    {"id": 1019, "title": "Financial Economics"},
    {"id": 1020, "title": "Health Economics"},
    {"id": 1021, "title": "Industry Economics and Industrial Organisation"},
    {"id": 1022, "title": "International Economics and International Finance"},
    {"id": 1023, "title": "Labour Economics"},
    {"id": 1024, "title": "Macroeconomics (incl. Monetary and Fiscal Theory)"},
    {"id": 1025, "title": "Public Economics- Public Choice"},
    {"id": 1026, "title": "Public Economics- Publically Provided Goods"},
    {"id": 1027, "title": "Public Economics- Taxation and Revenue"},
    {"id": 1028, "title": "Tourism Economics"},
    {"id": 1029, "title": "Transport Economics"},
    {"id": 1030, "title": "Urban and Regional Economics"},
    {"id": 1031, "title": "Welfare Economics"},
    {"id": 1032, "title": "Applied Economics not elsewhere classified"},
    {"id": 1033, "title": "Cross-Sectional Analysis"},
    {"id": 1034, "title": "Econometric and Statistical Methods"},
    {"id": 1035, "title": "Economic Models and Forecasting"},
    {"id": 1036, "title": "Panel Data Analysis"},
    {"id": 1037, "title": "Time-Series Analysis"},
    {"id": 1038, "title": "Econometrics not elsewhere classified"},
    {"id": 1040, "title": "Agricultural Biotechnology Diagnostics (incl. Biosensors)"},
    {"id": 1041, "title": "Agricultural Marine Biotechnology"},
    {"id": 1042, "title": "Agricultural Molecular Engineering of Nucleic Acids and Proteins"},
    {"id": 1043, "title": "Genetically Modified Animals"},
    {"id": 1044, "title": "Genetically Modified Field Crops and Pasture"},
    {"id": 1045, "title": "Genetically Modified Horticulture Plants"},
    {"id": 1046, "title": "Genetically Modified Trees"},
    {"id": 1047, "title": "Livestock Cloning"},
    {"id": 1048, "title": "Transgenesis"},
    {"id": 1049, "title": "Agricultural Biotechnology not elsewhere classified"},
    {"id": 1050, "title": "Biodiscovery"},
    {"id": 1051, "title": "Biological Control"},
    {"id": 1052, "title": "Bioremediation"},
    {"id": 1053, "title": "Environmental Biotechnology Diagnostics (incl. Biosensors)"},
    {"id": 1054, "title": "Environmental Marine Biotechnology"},
    {"id": 1055, "title": "Environmental Molecular Engineering of Nucleic Acids and Proteins"},
    {"id": 1056, "title": "Environmental Biotechnology not elsewhere classified"},
    {"id": 1057, "title": "Biocatalysis and Enzyme Technology"},
    {"id": 1058, "title": "Bioprocessing, Bioproduction and Bioproducts"},
    {"id": 1059, "title": "Fermentation"},
    {"id": 1060, "title": "Industrial Biotechnology Diagnostics (incl. Biosensors)"},
    {"id": 1061, "title": "Industrial Microbiology (incl. Biofeedstocks)"},
    {"id": 1062, "title": "Industrial Molecular Engineering of Nucleic Acids and Proteins"},
    {"id": 1063, "title": "Industrial Biotechnology not elsewhere classified"},
    {"id": 1064, "title": "Gene and Molecular Therapy"},
    {"id": 1065, "title": "Medical Biotechnology Diagnostics (incl. Biosensors)"},
    {"id": 1066, "title": "Medical Molecular Engineering of Nucleic Acids and Proteins"},
    {"id": 1067, "title": "Regenerative Medicine (incl. Stem Cells and Tissue Engineering)"},
    {"id": 1068, "title": "Medical Biotechnology not elsewhere classified"},
    {"id": 1069, "title": "Antennas and Propagation"},
    {"id": 1070, "title": "Broadband and Modem Technology"},
    {"id": 1071, "title": "Computer Communications Networks"},
    {"id": 1072, "title": "Data Communications"},
    {"id": 1073, "title": "Microwave and Millimetrewave Theory and Technology"},
    {"id": 1074, "title": "Optical Fibre Communications"},
    {"id": 1075, "title": "Optical Networks and Systems"},
    {"id": 1076, "title": "Satellite Communications"},
    {"id": 1077, "title": "Video Communications"},
    {"id": 1078, "title": "Wireless Communications"},
    {"id": 1079, "title": "Communications Technologies not elsewhere classified"},
    {"id": 1080, "title": "Arithmetic and Logic Structures"},
    {"id": 1081, "title": "Input, Output and Data Devices"},
    {"id": 1082, "title": "Logic Design"},
    {"id": 1083, "title": "Memory Structures"},
    {"id": 1084, "title": "Performance Evaluation; Testing and Simulation of Reliability"},
    {"id": 1085, "title": "Processor Architectures"},
    {"id": 1086, "title": "Computer Hardware not elsewhere classified"},
    {"id": 1087, "title": "Environmental Nanotechnology"},
    {"id": 1088, "title": "Molecular and Organic Electronics"},
    {"id": 1089, "title": "Nanobiotechnology"},
    {"id": 1090, "title": "Nanoelectromechanical Systems"},
    {"id": 1091, "title": "Nanoelectronics"},
    {"id": 1092, "title": "Nanofabrication, Growth and Self Assembly"},
    {"id": 1093, "title": "Nanomanufacturing"},
    {"id": 1094, "title": "Nanomaterials"},
    {"id": 1095, "title": "Nanomedicine"},
    {"id": 1096, "title": "Nanometrology"},
    {"id": 1097, "title": "Nanophotonics"},
    {"id": 1098, "title": "Nanoscale Characterisation"},
    {"id": 1099, "title": "Nanotoxicology, Health and Safety"},
    {"id": 1100, "title": "Nanotechnology not elsewhere classified"},
    {"id": 1102, "title": "Architectural Design"},
    {"id": 1103, "title": "Architectural Heritage and Conservation"},
    {"id": 1104, "title": "Architectural History and Theory"},
    {"id": 1105, "title": "Architectural Science and Technology (incl. Acoustics, Lighting, Structure and Ecologically Sustainable Design)"},
    {"id": 1106, "title": "Architecture Management"},
    {"id": 1107, "title": "Interior Design"},
    {"id": 1108, "title": "Landscape Architecture"},
    {"id": 1109, "title": "Architecture not elsewhere classified"},
    {"id": 1110, "title": "Building Construction Management and Project Planning"}
]